version: '2'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    links:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile

  nginx:
    ports:
      - 80:80
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - backend
      - frontend

  mongodb:
    image: mongo
    restart: unless-stopped
